name: edgex-app-service-configurable
base: core20
license: Apache-2.0
adopt-info: metadata

architectures:
  - build-on: amd64
  - build-on: arm64

grade: stable
confinement: strict

# 1: edinburgh
# 2: fuji
# 3: geneva, hanoi
# 4: ireland
epoch: 4

slots:
  edgex-secretstore-token:
    interface: content
    content: edgex-secretstore-token
    source:
      write: 
        - $SNAP_DATA/app-http-export
        - $SNAP_DATA/app-mqtt-export
        - $SNAP_DATA/app-external-mqtt-trigger
        - $SNAP_DATA/app-functional-tests
        - $SNAP_DATA/app-push-to-core
        - $SNAP_DATA/app-rules-engine

apps:
  app-service-configurable:
    adapter: full
    command: bin/service-wrapper.sh
    command-chain:
      - bin/startup-env-var.sh
      - bin/security-secret-store-env-var.sh
    daemon: simple
    install-mode: disable
    plugs: [network, network-bind]

plugs:
  app-config:
    interface: content
    target: $SNAP_DATA/config

parts:
  app-service-config:
    after: [metadata]
    source: .
    plugin: make
    build-packages: [gcc, git, libzmq3-dev, pkg-config]
    build-snaps:
      - go/1.17/stable
    stage-packages: [libzmq5]
    override-build: |
      cd $SNAPCRAFT_PART_SRC

      make tidy
      make build

      # install the service binary
      install -DT "./app-service-configurable" \
         "$SNAPCRAFT_PART_INSTALL/bin/app-service-configurable"

      # create config dirs
      find ./res -maxdepth 1 -type d -exec install -d "$SNAPCRAFT_PART_INSTALL/config/"{} \;

      # replace relative log paths in configuration.toml files with fully qualified paths
      # prefixed with $SNAP_COMMON
      find ./res -name "configuration.toml" | \
          while read fname; do
               cat "$fname" | sed -e s:\./logs/:\\'$SNAP_COMMON/'\: > \
              "$SNAPCRAFT_PART_INSTALL/config/$fname"
          done

      install -DT "./Attribution.txt" \
         "$SNAPCRAFT_PART_INSTALL/usr/share/doc/app-service-configurable/Attribution.txt"
      install -DT "./LICENSE" \
         "$SNAPCRAFT_PART_INSTALL/usr/share/doc/app-service-configurable/LICENSE"

  config-common:
    plugin: dump
    source: snap/local/runtime-helpers

  metadata:
    plugin: nil
    build-packages: [curl]
    override-pull: |
      # download the metadata in AppStream format
      curl --silent --show-error --location --remote-name \
        https://raw.githubusercontent.com/canonical/edgex-snap-metadata/appstream/edgex-app-service-configurable.metainfo.xml

      # get the version from git tag
      cd $SNAPCRAFT_PROJECT_DIR
      if git describe ; then
        VERSION=$(git describe --tags --abbrev=0 | sed 's/v//')
      else
        VERSION="0.0.0"
      fi
      
      # write version to file for the build
      echo $VERSION > ./VERSION
      snapcraftctl set-version $VERSION
    parse-info: [edgex-app-service-configurable.metainfo.xml]

  hooks:
    source: snap/local/hooks
    plugin: make
    override-build: |
      cd $SNAPCRAFT_PART_SRC
      make build
      install -DT ./cmd/configure/configure "$SNAPCRAFT_PART_INSTALL/snap/hooks/configure"
      install -DT ./cmd/install/install "$SNAPCRAFT_PART_INSTALL/snap/hooks/install"
